name: test-policies
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  test-policies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
          | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
          && echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" \
          | sudo tee /etc/apt/sources.list.d/ngrok.list \
          && sudo apt update \
          && sudo apt install ngrok
      - name: Test Policies
        env: # Or as an environment variable 
          NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
        run: |
          cd $GITHUB_WORKSPACE
          ./scripts/test-policies.sh
